// 10 pre-built payslip template designs
// Each template defines visual style properties used at render time

export interface PayslipDesignTemplate {
  id: string;
  name: string;
  description: string;
  fontFamily: string;
  headerFont: string;
  accentColor: string;
  headerBg: string;
  headerText: string;
  borderStyle: string;
  tableHeaderBg: string;
  tableHeaderText: string;
  footerBg: string;
  footerText: string;
  logoPosition: 'left' | 'center' | 'right';
  style: 'corporate' | 'modern' | 'minimal' | 'bold' | 'elegant';
}

export const PAYSLIP_DESIGN_TEMPLATES: PayslipDesignTemplate[] = [
  {
    id: 'classic-corporate',
    name: 'Classic Corporate',
    description: 'Traditional corporate style with navy blue tones',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Playfair Display', serif",
    accentColor: '#1e3a5f',
    headerBg: '#1e3a5f',
    headerText: '#ffffff',
    borderStyle: '1px solid #d1d5db',
    tableHeaderBg: '#f0f4f8',
    tableHeaderText: '#1e3a5f',
    footerBg: '#f8fafc',
    footerText: '#64748b',
    logoPosition: 'left',
    style: 'corporate',
  },
  {
    id: 'modern-teal',
    name: 'Modern Teal',
    description: 'Clean modern design with teal accents',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Inter', sans-serif",
    accentColor: '#0d9488',
    headerBg: '#0d9488',
    headerText: '#ffffff',
    borderStyle: '1px solid #e2e8f0',
    tableHeaderBg: '#f0fdfa',
    tableHeaderText: '#0d9488',
    footerBg: '#f0fdfa',
    footerText: '#475569',
    logoPosition: 'left',
    style: 'modern',
  },
  {
    id: 'minimal-slate',
    name: 'Minimal Slate',
    description: 'Ultra-minimal with subtle gray tones',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Inter', sans-serif",
    accentColor: '#475569',
    headerBg: '#ffffff',
    headerText: '#1e293b',
    borderStyle: '1px solid #e2e8f0',
    tableHeaderBg: '#f8fafc',
    tableHeaderText: '#334155',
    footerBg: '#ffffff',
    footerText: '#94a3b8',
    logoPosition: 'center',
    style: 'minimal',
  },
  {
    id: 'bold-indigo',
    name: 'Bold Indigo',
    description: 'Strong indigo header with modern typography',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Fraunces', serif",
    accentColor: '#4f46e5',
    headerBg: '#4f46e5',
    headerText: '#ffffff',
    borderStyle: '2px solid #e0e7ff',
    tableHeaderBg: '#eef2ff',
    tableHeaderText: '#4338ca',
    footerBg: '#eef2ff',
    footerText: '#6366f1',
    logoPosition: 'left',
    style: 'bold',
  },
  {
    id: 'elegant-charcoal',
    name: 'Elegant Charcoal',
    description: 'Sophisticated dark theme with gold accents',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Playfair Display', serif",
    accentColor: '#1c1917',
    headerBg: '#1c1917',
    headerText: '#fafaf9',
    borderStyle: '1px solid #d6d3d1',
    tableHeaderBg: '#f5f5f4',
    tableHeaderText: '#1c1917',
    footerBg: '#1c1917',
    footerText: '#a8a29e',
    logoPosition: 'right',
    style: 'elegant',
  },
  {
    id: 'fresh-emerald',
    name: 'Fresh Emerald',
    description: 'Vibrant green-themed professional design',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Inter', sans-serif",
    accentColor: '#059669',
    headerBg: '#059669',
    headerText: '#ffffff',
    borderStyle: '1px solid #d1fae5',
    tableHeaderBg: '#ecfdf5',
    tableHeaderText: '#047857',
    footerBg: '#ecfdf5',
    footerText: '#6b7280',
    logoPosition: 'left',
    style: 'modern',
  },
  {
    id: 'warm-amber',
    name: 'Warm Amber',
    description: 'Welcoming warm tones with amber highlights',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Fraunces', serif",
    accentColor: '#b45309',
    headerBg: '#78350f',
    headerText: '#fef3c7',
    borderStyle: '1px solid #fde68a',
    tableHeaderBg: '#fffbeb',
    tableHeaderText: '#92400e',
    footerBg: '#fffbeb',
    footerText: '#92400e',
    logoPosition: 'center',
    style: 'bold',
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Premium feel with deep purple accents',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Playfair Display', serif",
    accentColor: '#7c3aed',
    headerBg: '#5b21b6',
    headerText: '#f5f3ff',
    borderStyle: '1px solid #ddd6fe',
    tableHeaderBg: '#f5f3ff',
    tableHeaderText: '#6d28d9',
    footerBg: '#f5f3ff',
    footerText: '#7c3aed',
    logoPosition: 'left',
    style: 'elegant',
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    description: 'Calming blue gradient with clean lines',
    fontFamily: "'Inter', sans-serif",
    headerFont: "'Inter', sans-serif",
    accentColor: '#2563eb',
    headerBg: '#1d4ed8',
    headerText: '#ffffff',
    borderStyle: '1px solid #bfdbfe',
    tableHeaderBg: '#eff6ff',
    tableHeaderText: '#1e40af',
    footerBg: '#eff6ff',
    footerText: '#3b82f6',
    logoPosition: 'left',
    style: 'corporate',
  },
  {
    id: 'monospace-tech',
    name: 'Monospace Tech',
    description: 'Technical style with monospace font emphasis',
    fontFamily: "'Space Mono', monospace",
    headerFont: "'Space Mono', monospace",
    accentColor: '#18181b',
    headerBg: '#18181b',
    headerText: '#a1a1aa',
    borderStyle: '1px solid #3f3f46',
    tableHeaderBg: '#27272a',
    tableHeaderText: '#e4e4e7',
    footerBg: '#18181b',
    footerText: '#71717a',
    logoPosition: 'left',
    style: 'modern',
  },
];
